In [1]:
# Import libraries

import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [6]:
df= pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Hamoye Notebooks/Regression/Quiz/energydata_complete.csv')

df.head(25)

date  Appliances  lights         T1       RH_1         T2  \
0   2016-01-11 17:00:00          60      30  19.890000  47.596667  19.200000   
1   2016-01-11 17:10:00          60      30  19.890000  46.693333  19.200000   
2   2016-01-11 17:20:00          50      30  19.890000  46.300000  19.200000   
3   2016-01-11 17:30:00          50      40  19.890000  46.066667  19.200000   
4   2016-01-11 17:40:00          60      40  19.890000  46.333333  19.200000   
5   2016-01-11 17:50:00          50      40  19.890000  46.026667  19.200000   
6   2016-01-11 18:00:00          60      50  19.890000  45.766667  19.200000   
7   2016-01-11 18:10:00          60      50  19.856667  45.560000  19.200000   
8   2016-01-11 18:20:00          60      40  19.790000  45.597500  19.200000   
9   2016-01-11 18:30:00          70      40  19.856667  46.090000  19.230000   
10  2016-01-11 18:40:00         230      70  19.926667  45.863333  19.356667   
11  2016-01-11 18:50:00         580      60  20.066667  46.396667  19.426667   
12  2016-01-11 19:00:00         430      50  20.133333  48.000000  19.566667   
13  2016-01-11 19:10:00         250      40  20.260000  52.726667  19.730000   
14  2016-01-11 19:20:00         100      10  20.426667  55.893333  19.856667   
15  2016-01-11 19:30:00         100      10  20.566667  53.893333  20.033333   
16  2016-01-11 19:40:00          90      10  20.730000  52.660000  20.166667   
17  2016-01-11 19:50:00          70      30  20.856667  53.660000  20.200000   
18  2016-01-11 20:00:00          80      30  20.890000  51.193333  20.200000   
19  2016-01-11 20:10:00         140      40  20.890000  49.800000  20.200000   
20  2016-01-11 20:20:00         120      20  20.890000  48.433333  20.200000   
21  2016-01-11 20:30:00         190      40  20.963333  47.633333  20.260000   
22  2016-01-11 20:40:00         110      40  21.033333  47.063333  20.290000   
23  2016-01-11 20:50:00         110      40  21.100000  46.596667  20.356667   
24  2016-01-11 21:00:00         110      30  21.133333  46.060000  20.426667   

         RH_2         T3       RH_3         T4  ...         T9       RH_9  \
0   44.790000  19.790000  44.730000  19.000000  ...  17.033333  45.530000   
1   44.722500  19.790000  44.790000  19.000000  ...  17.066667  45.560000   
2   44.626667  19.790000  44.933333  18.926667  ...  17.000000  45.500000   
3   44.590000  19.790000  45.000000  18.890000  ...  17.000000  45.400000   
4   44.530000  19.790000  45.000000  18.890000  ...  17.000000  45.400000   
5   44.500000  19.790000  44.933333  18.890000  ...  17.000000  45.290000   
6   44.500000  19.790000  44.900000  18.890000  ...  17.000000  45.290000   
7   44.500000  19.730000  44.900000  18.890000  ...  17.000000  45.290000   
8   44.433333  19.730000  44.790000  18.890000  ...  17.000000  45.290000   
9   44.400000  19.790000  44.863333  18.890000  ...  17.000000  45.290000   
10  44.400000  19.790000  44.900000  18.890000  ...  17.000000  45.290000   
11  44.400000  19.790000  44.826667  19.000000  ...  16.890000  45.290000   
12  44.400000  19.890000  44.900000  19.000000  ...  16.963333  45.290000   
13  45.100000  19.890000  45.493333  19.000000  ...  16.890000  45.326667   
14  45.833333  20.033333  47.526667  19.000000  ...  16.890000  45.345000   
15  46.756667  20.100000  48.466667  19.000000  ...  16.890000  45.326667   
16  47.223333  20.200000  48.530000  18.926667  ...  16.890000  45.290000   
17  47.056667  20.200000  48.447500  18.890000  ...  16.890000  45.290000   
18  46.330000  20.200000  48.193333  18.963333  ...  16.890000  45.200000   
19  46.026667  20.166667  47.633333  19.033333  ...  16.890000  45.200000   
20  45.722500  20.166667  47.300000  19.175000  ...  16.890000  45.126667   
21  45.530000  20.200000  47.026667  19.260000  ...  16.890000  45.126667   
22  45.223333  20.260000  46.826667  19.323333  ...  16.890000  45.060000   
23  44.963333  20.290000  46.633333  19.390000  ...  16.890000  45.000000   
24  44.760000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [7]:
# simple_lin_reg

df_1 = df[['T2', 'T6']]

df_1.head(10)

T2        T6
0  19.20  7.026667
1  19.20  6.833333
2  19.20  6.560000
3  19.20  6.433333
4  19.20  6.366667
5  19.20  6.300000
6  19.20  6.263333
7  19.20  6.190000
8  19.20  6.123333
9  19.23  6.190000

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [11]:
df_2 = df.drop(columns=['date', 'lights'])

normalised_df = pd.DataFrame(scaler.fit_transform(df_2), columns = df_2.columns)

In [13]:
normalised_df.head()

Appliances       T1      RH_1        T2      RH_2        T3      RH_3  \
0    0.046729  0.32735  0.566187  0.225345  0.684038  0.215188  0.746066   
1    0.046729  0.32735  0.541326  0.225345  0.682140  0.215188  0.748871   
2    0.037383  0.32735  0.530502  0.225345  0.679445  0.215188  0.755569   
3    0.037383  0.32735  0.524080  0.225345  0.678414  0.215188  0.758685   
4    0.046729  0.32735  0.531419  0.225345  0.676727  0.215188  0.758685   

         T4      RH_4        T5  ...        T9      RH_9     T_out  \
0  0.351351  0.764262  0.175506  ...  0.223032  0.677290  0.372990   
1  0.351351  0.782437  0.175506  ...  0.226500  0.678532  0.369239   
2  0.344745  0.778062  0.175506  ...  0.219563  0.676049  0.365488   
3  0.341441  0.770949  0.175506  ...  0.219563  0.671909  0.361736   
4  0.341441  0.762697  0.178691  ...  0.219563  0.671909  0.357985   

   Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0     0.097674  0.894737   0.500000    0.953846   0.538462  0.265449  0.265449  
1     0.100000  0.894737   0.476190    0.894872   0.533937  0.372083  0.372083  
2     0.102326  0.894737   0.452381    0.835897   0.529412  0.572848  0.572848  
3     0.104651  0.894737   0.428571    0.776923   0.524887  0.908261  0.908261  
4     0.106977  0.894737   0.404762    0.717949   0.520362  0.201611  0.201611  

[5 rows x 27 columns]

In [14]:
features_df = normalised_df.drop(columns=['Appliances'])

App_target = normalised_df['Appliances']

In [15]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(features_df,
                                                    App_target, test_size=0.3,
                                                    random_state=42)

In [16]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(x_train, y_train)

LinearRegression()

In [17]:
predicted_values = linear_model.predict(x_test)

In [18]:
predicted_values[:10]

array([0.03322207, 0.24411599, 0.03400024, 0.10537699, 0.02336017,
       0.16282096, 0.07428805, 0.16370529, 0.07506936, 0.1017172 ])

In [19]:
from sklearn.metrics import mean_absolute_error

mae =  mean_absolute_error(y_test, predicted_values)

round(mae,2)

0.05

In [20]:
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, predicted_values))

round(rmse, 3)

0.088

In [21]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, predicted_values)

round(r_squared, 2)

0.15

In [22]:
from sklearn.linear_model import Ridge

ridge_reg = Ridge(alpha = 0.4)

ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.4)

In [23]:
pred_2 = ridge_reg.predict(x_test)

pred_2[:10]

array([0.03321872, 0.24043824, 0.03461337, 0.10707126, 0.02394352,
       0.15925248, 0.07422873, 0.16389752, 0.07505956, 0.10099954])

In [24]:
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, pred_2))

round(rmse, 3)

0.088

In [25]:
from sklearn.linear_model import Lasso

lasso_reg = Lasso(alpha = 0.001)

lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.001)

In [28]:
pred_3 = lasso_reg.predict(x_test)

pred_3[:10]

array([0.07370267, 0.08143458, 0.07716072, 0.08848143, 0.07065504,
       0.08493887, 0.09061999, 0.09087763, 0.07732193, 0.07474244])

In [29]:
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, pred_3))

round(rmse, 3)

0.094

In [30]:
def get_weight_df(model, feat, col_name):
  # this function returns the weight of every feature
  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

lasso_weights_df = get_weight_df(lasso_reg, x_train, 'Lasso_Weight')

In [31]:
lasso_weights_df

Features  Lasso_Weight
0        RH_out     -0.049557
1          RH_8     -0.000110
2            T1      0.000000
3     Tdewpoint      0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      0.002912
25         RH_1      0.017880